# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Default_settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Default_settings_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 343)
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 40, 361, 241))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(20, 20, 20, 5)
        self.formLayout.setVerticalSpacing(15)
        self.formLayout.setObjectName("formLayout")
        self.label_called_number = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_called_number.setObjectName("label_called_number")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_called_number)
        self.edit_called_number = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.edit_called_number.setText("")
        self.edit_called_number.setObjectName("edit_called_number")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.edit_called_number)
        self.label_test_interval = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_test_interval.setObjectName("label_Default_mes")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_test_interval)
        self.edit_test_interval = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.edit_test_interval.setObjectName("edit_test_interval")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.edit_test_interval)
        self.label_times = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_times.setTextFormat(QtCore.Qt.AutoText)
        self.label_times.setObjectName("Label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_times)
        self.edit_times = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.edit_times.setObjectName("LineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.edit_times)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(210, 290, 171, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.button_ok = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.button_ok.setObjectName("button_ok")
        self.horizontalLayout_2.addWidget(self.button_ok)
        self.button_cancel = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.button_cancel.setObjectName("button_cancel")
        self.horizontalLayout_2.addWidget(self.button_cancel)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "默认设置"))
        self.label_called_number.setText(_translate("Dialog", "被叫号码"))
        self.label_test_interval.setText(_translate("Dialog", "通话测试间隔（秒）"))
        self.label_times.setText(_translate("Dialog", "默认测试次数"))
        self.button_ok.setText(_translate("Dialog", "OK"))
        self.button_cancel.setText(_translate("Dialog", "Cancel"))
