CP_test:
  FailAutoStop: false
  TT_path: ''
  TTlog: false
  Trace_path: ''
  Tracelog: false
call_no_answer:
  interval: ''
  number: ''
  ring_time: ''
  timeout: ''
call_reject:
  interval: ''
  number: ''
  ring_time: ''
  timeout: ''
call_to_answer:
  hold: ''
  interval: ''
  number: ''
  timeout: ''
caller_hangs_up:
  hold: ''
  interval: ''
  number: ''
  timeout: ''
config_BT:
  BT_name: ihblu
config_WIFI:
  WIFI_PWD: '12345678'
  WIFI_SSID: jiaze2.4G
  WIFI_interval: '100'
db_info:
  ap_table: ap_testcases
  charset: utf8
  cp_table: cp_testcases
  database: test_cases
  host: 10.86.1.162
  password: root
  port: 10001
  user: root
