CP_test:
  FailAutoStop: false
  TT_path: ''
  TTlog: false
  Trace_path: ''
  Tracelog: false
call_no_answer:
  interval: '10'
  number: '18701997306'
  ring_time: '10'
  timeout: '60'
call_reject:
  interval: '15'
  number: '18701997306'
  ring_time: '20'
  timeout: '80'
call_to_answer:
  hold: '20'
  interval: '15'
  number: '10000'
  timeout: '80'
caller_hangs_up:
  hold: '20'
  interval: '15'
  number: '18701997306'
  timeout: '80'
config_BT:
  BT_name: ihblu
config_WIFI:
  WIFI_PWD: '12345678'
  WIFI_SSID: jiaze2.4G
  WIFI_interval: '100'
db_info:
  ap_table: ap_testcases
  charset: utf8
  cp_table: cp_testcases
  database: test_cases
  host: 10.86.1.162
  password: root
  port: 10001
  user: root
