CP_test:
  TT_path: D:/software/TT/bin/TT.exe
  Trace_path: "D:/software/Trace\uFF08\u5DE5\u5177\uFF09/Trace/Trace.exe"
  use_COM: COM8
config_BT:
  BT_name: ihblu
config_WIFI:
  WIFI_PWD: '12345678'
  WIFI_SSID: jiaze2.4G
  WIFI_interval: '100'
config_call:
  call_hold: '10'
  call_interval: '10'
  call_number: '18701997306'
  call_timeout: '120'
db_info:
  ap_table: ap_testcases
  charset: utf8
  cp_table: cp_testcases
  database: test_cases
  host: 10.86.1.162
  password: root
  port: 10001
  user: root
