# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'caseTableUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_Testcase_table(object):
    def setupUi(self, Testcase_table):
        Testcase_table.setObjectName("Testcase_table")
        Testcase_table.resize(510, 724)
        Testcase_table.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(Testcase_table)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.Btn_cancel_case = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.Btn_cancel_case.setFont(font)
        self.Btn_cancel_case.setObjectName("Btn_cancel_case")
        self.gridLayout.addWidget(self.Btn_cancel_case, 1, 3, 1, 1)
        self.Btn_config_case = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.Btn_config_case.setFont(font)
        self.Btn_config_case.setObjectName("Btn_config_case")
        self.gridLayout.addWidget(self.Btn_config_case, 1, 0, 1, 1)
        self.TreeWidget_case = QtWidgets.QTreeWidget(self.centralwidget)
        self.TreeWidget_case.setObjectName("TreeWidget_case")
        self.TreeWidget_case.setColumnCount(2)
        self.TreeWidget_case.setColumnWidth(0, 300)
        self.TreeWidget_case.setColumnWidth(1, 100)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 255, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.TreeWidget_case.headerItem().setFont(0, font)
        self.TreeWidget_case.headerItem().setFont(1, font)
        self.TreeWidget_case.headerItem().setBackground(0, QtGui.QColor(255, 170, 127))
        self.TreeWidget_case.headerItem().setBackground(1, QtGui.QColor(255, 170, 127))
        self.TreeWidget_case.headerItem().setForeground(0, brush)
        self.TreeWidget_case.headerItem().setForeground(1, brush)

        self.gridLayout.addWidget(self.TreeWidget_case, 0, 0, 1, 4)
        self.Btn_save_case = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.Btn_save_case.setFont(font)
        self.Btn_save_case.setObjectName("Btn_save_case")
        self.gridLayout.addWidget(self.Btn_save_case, 1, 2, 1, 1)
        Testcase_table.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Testcase_table)
        self.statusbar.setObjectName("statusbar")
        Testcase_table.setStatusBar(self.statusbar)

        self.retranslateUi(Testcase_table)
        QtCore.QMetaObject.connectSlotsByName(Testcase_table)

    def retranslateUi(self, Testcase_table):
        _translate = QtCore.QCoreApplication.translate
        Testcase_table.setWindowTitle(_translate("Testcase_table", "用例表"))

        self.TreeWidget_case.headerItem().setText(0, _translate("Testcase_table", "用例标题"))
        self.TreeWidget_case.headerItem().setText(1, _translate("Testcase_table", "配置"))
        __sortingEnabled = self.TreeWidget_case.isSortingEnabled()
        self.TreeWidget_case.setSortingEnabled(False)

        self.TreeWidget_case.setSortingEnabled(__sortingEnabled)
        self.Btn_save_case.setText(_translate("Testcase_table", "保存"))
        self.Btn_cancel_case.setText(_translate("Testcase_table", "取消"))
        self.Btn_config_case.setText(_translate("Testcase_table", "配置"))
