# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ensureCaseTable.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EnsureCase_table(object):
    def setupUi(self, EnsureCase_table):
        EnsureCase_table.setObjectName("EnsureCase_table")
        EnsureCase_table.resize(520, 661)
        font = QtGui.QFont()
        font.setPointSize(9)
        EnsureCase_table.setFont(font)
        EnsureCase_table.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        EnsureCase_table.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(EnsureCase_table)
        self.centralwidget.setObjectName("centralwidget")
        self.ListWidget_ensureTable = QtWidgets.QListWidget(self.centralwidget)
        self.ListWidget_ensureTable.setGeometry(QtCore.QRect(10, 10, 461, 601))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ListWidget_ensureTable.setFont(font)
        self.ListWidget_ensureTable.setObjectName("ListWidget_ensureTable")

        self.Btn_ensureTable_cancel = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_ensureTable_cancel.setGeometry(QtCore.QRect(380, 620, 93, 28))
        self.Btn_ensureTable_cancel.setObjectName("Btn_ensureTable_cancel")
        self.Btn_ensure_ok = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_ensure_ok.setGeometry(QtCore.QRect(280, 620, 93, 28))
        self.Btn_ensure_ok.setObjectName("Btn_ensure_ok")

        self.Btn_ensure_up = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_ensure_up.setGeometry(QtCore.QRect(480, 220, 31, 31))
        self.Btn_ensure_up.setObjectName("Btn_ensure_up")
        self.Btn_ensure_down = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_ensure_down.setGeometry(QtCore.QRect(480, 290, 31, 31))
        self.Btn_ensure_down.setObjectName("Btn_ensure_down")
        EnsureCase_table.setCentralWidget(self.centralwidget)

        self.retranslateUi(EnsureCase_table)
        QtCore.QMetaObject.connectSlotsByName(EnsureCase_table)

    def retranslateUi(self, EnsureCase_table):
        _translate = QtCore.QCoreApplication.translate
        EnsureCase_table.setWindowTitle(_translate("EnsureCase_table", "待测用例"))
        __sortingEnabled = self.ListWidget_ensureTable.isSortingEnabled()
        self.ListWidget_ensureTable.setSortingEnabled(False)

        self.ListWidget_ensureTable.setSortingEnabled(__sortingEnabled)
        self.Btn_ensureTable_cancel.setText(_translate("EnsureCase_table", "取消"))
        self.Btn_ensure_ok.setText(_translate("EnsureCase_table", "确认"))
        self.Btn_ensure_up.setText(_translate("EnsureCase_table", "↑"))
        self.Btn_ensure_down.setText(_translate("EnsureCase_table", "↓"))
