# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

import Word


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(968, 761)
        MainWindow.setStyleSheet("background-color: white;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)

        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(11)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("background-color: white;\n"
                                     "border-color: rgb(0, 0, 0);")
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabBarAutoHide(True)
        self.tabWidget.setObjectName("tabWidget")
        self.AP = QtWidgets.QWidget()
        self.AP.setStyleSheet("background-color: white;")
        self.AP.setObjectName("AP")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.AP)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")


        self.GroupBox_AP_test = QtWidgets.QGroupBox(self.AP)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GroupBox_AP_test.sizePolicy().hasHeightForWidth())
        self.GroupBox_AP_test.setSizePolicy(sizePolicy)
        self.GroupBox_AP_test.setMinimumSize(QtCore.QSize(240, 0))
        self.GroupBox_AP_test.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.GroupBox_AP_test.setTabletTracking(False)
        self.GroupBox_AP_test.setFocusPolicy(QtCore.Qt.NoFocus)
        self.GroupBox_AP_test.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.GroupBox_AP_test.setStyleSheet("border:none")
        self.GroupBox_AP_test.setTitle("")
        self.GroupBox_AP_test.setObjectName("GroupBox_AP_test")
        self.Btn_dev_check = QtWidgets.QPushButton(self.GroupBox_AP_test)
        self.Btn_dev_check.setGeometry(QtCore.QRect(20, 20, 203, 43))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_dev_check.sizePolicy().hasHeightForWidth())
        self.Btn_dev_check.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Btn_dev_check.setFont(font)
        self.Btn_dev_check.setStyleSheet("background-color: white;\n"
                                         "border-style: outset;\n"
                                         "border-width: 2px;\n"
                                         "border-radius: 10px;\n"
                                         "border-color: #5A8EF4;\n"
                                         "color:#5A8EF4;\n"
                                         "font: bold 18px;\n"
                                         "")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/ue_select.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Btn_dev_check.setIcon(icon)
        self.Btn_dev_check.setIconSize(QtCore.QSize(25, 25))
        self.Btn_dev_check.setCheckable(False)
        self.Btn_dev_check.setDefault(False)
        self.Btn_dev_check.setObjectName("Btn_dev_check")
        self.ComboBox_dev_select = QtWidgets.QComboBox(self.GroupBox_AP_test)
        self.ComboBox_dev_select.setGeometry(QtCore.QRect(20, 80, 203, 43))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComboBox_dev_select.sizePolicy().hasHeightForWidth())
        self.ComboBox_dev_select.setSizePolicy(sizePolicy)
        self.ComboBox_dev_select.setStyleSheet("background-color: white;\n"
                                               "border-style: outset;\n"
                                               "border-width: 2px;\n"
                                               "border-radius: 10px;\n"
                                               "border-color: #5A8EF4;\n"
                                               "color:#5A8EF4;\n"
                                               "font: bold 16px;\n"
                                               "min-width: 10em;")
        self.ComboBox_dev_select.setEditable(False)
        self.ComboBox_dev_select.setCurrentText("")
        self.ComboBox_dev_select.setObjectName("ComboBox_dev_select")
        self.Btn_AP_runTest = QtWidgets.QPushButton(self.GroupBox_AP_test)
        self.Btn_AP_runTest.setEnabled(True)
        self.Btn_AP_runTest.setGeometry(QtCore.QRect(20, 510, 203, 43))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_AP_runTest.sizePolicy().hasHeightForWidth())
        self.Btn_AP_runTest.setSizePolicy(sizePolicy)
        self.Btn_AP_runTest.setMinimumSize(QtCore.QSize(184, 0))
        self.Btn_AP_runTest.setMaximumSize(QtCore.QSize(203, 16777215))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Btn_AP_runTest.setFont(font)
        self.Btn_AP_runTest.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Btn_AP_runTest.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 #EEB84B, stop:0.95 #EFD560);\n"
            "border-style: outset;\n"
            "border-width: 2px;\n"
            "border-radius: 10px;\n"
            "border-color: #F7B500;\n"
            "color:white;\n"
            "font: bold 18px;\n"
            "min-width: 10em;")
        self.Btn_AP_runTest.setObjectName("Btn_AP_runTest")
        self.Btn_AP_stopTest = QtWidgets.QPushButton(self.GroupBox_AP_test)
        self.Btn_AP_stopTest.setGeometry(QtCore.QRect(20, 570, 93, 35))
        self.Btn_AP_stopTest.setMinimumSize(QtCore.QSize(93, 0))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Btn_AP_stopTest.setFont(font)
        self.Btn_AP_stopTest.setStyleSheet("background-color: white;\n"
                                           "border-style: outset;\n"
                                           "border-width: 2px;\n"
                                           "border-radius: 10px;\n"
                                           "border-color: #E02020;\n"
                                           "color:#E02020;\n"
                                           "font: bold 16px;\n"
                                           "min-width: 10em;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Btn_AP_stopTest.setIcon(icon1)
        self.Btn_AP_stopTest.setIconSize(QtCore.QSize(25, 25))
        self.Btn_AP_stopTest.setObjectName("Btn_AP_stopTest")
        self.Label_AP_test_times = QtWidgets.QLabel(self.GroupBox_AP_test)
        self.Label_AP_test_times.setGeometry(QtCore.QRect(30, 460, 81, 25))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(11)
        self.Label_AP_test_times.setFont(font)
        self.Label_AP_test_times.setObjectName("Label_AP_test_times")
        self.Ledit_AP_test_times = QtWidgets.QLineEdit(self.GroupBox_AP_test)
        self.Ledit_AP_test_times.setEnabled(True)
        self.Ledit_AP_test_times.setGeometry(QtCore.QRect(110, 450, 101, 43))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Ledit_AP_test_times.sizePolicy().hasHeightForWidth())
        self.Ledit_AP_test_times.setSizePolicy(sizePolicy)
        self.Ledit_AP_test_times.setMaximumSize(QtCore.QSize(101, 16777215))
        self.Ledit_AP_test_times.setMouseTracking(False)
        self.Ledit_AP_test_times.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Ledit_AP_test_times.setStyleSheet("background-color: white;\n"
                                               "border-style: outset;\n"
                                               "border-width: 2px;\n"
                                               "border-radius: 4px;\n"
                                               "border-color: rgb(0, 170, 255);\n"
                                               "color:rgb(0, 170, 255);\n"
                                               "font: bold 18px;")
        self.Ledit_AP_test_times.setAlignment(QtCore.Qt.AlignCenter)
        self.Ledit_AP_test_times.setObjectName("Ledit_AP_test_times")
        self.Btn_select_ap_case = QtWidgets.QPushButton(self.GroupBox_AP_test)
        self.Btn_select_ap_case.setGeometry(QtCore.QRect(20, 380, 200, 51))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Btn_select_ap_case.setFont(font)
        self.Btn_select_ap_case.setStyleSheet("background-color: rgb(69, 119, 255);\n"
                                              "border-style: outset;\n"
                                              "border-radius: 10px;\n"
                                              "color:white;\n"
                                              "font: bold 18px;\n"
                                              "min-width: 10em;")
        self.Btn_select_ap_case.setObjectName("Btn_select_ap_case")
        self.textBrowser = QtWidgets.QTextBrowser(self.GroupBox_AP_test)
        self.textBrowser.setGeometry(QtCore.QRect(20, 160, 203, 201))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("border:none;\n"
                                       "background-color: #EAEEF6;\n"
                                       "border-color: #ADBFE2;\n"
                                       "border-style: outset;\n"
                                       "border-width: 2px;\n"
                                       "border-radius: 5px;\n"
                                       "min-width: 10em;")
        self.textBrowser.setReadOnly(False)
        self.textBrowser.setMarkdown("")
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout_5.addWidget(self.GroupBox_AP_test)
        self.AP_verLayout_recv = QtWidgets.QVBoxLayout()
        self.AP_verLayout_recv.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.AP_verLayout_recv.setContentsMargins(0, 0, 0, 0)
        self.AP_verLayout_recv.setObjectName("AP_verLayout_recv")
        self.GroupBox_AP_recv = QtWidgets.QGroupBox(self.AP)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.GroupBox_AP_recv.sizePolicy().hasHeightForWidth())
        self.GroupBox_AP_recv.setSizePolicy(sizePolicy)
        self.GroupBox_AP_recv.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setFamily("等线")
        self.GroupBox_AP_recv.setFont(font)
        self.GroupBox_AP_recv.setObjectName("GroupBox_AP_recv")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.GroupBox_AP_recv)
        self.verticalLayout_5.setContentsMargins(10, 5, 10, 5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.TextBrowser_AP_recv = QtWidgets.QTextBrowser(self.GroupBox_AP_recv)
        self.TextBrowser_AP_recv.setMinimumSize(QtCore.QSize(300, 0))
        self.TextBrowser_AP_recv.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.TextBrowser_AP_recv.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.TextBrowser_AP_recv.setMarkdown("")
        self.TextBrowser_AP_recv.setObjectName("TextBrowser_AP_recv")
        self.verticalLayout_5.addWidget(self.TextBrowser_AP_recv)
        self.AP_verLayout_recv.addWidget(self.GroupBox_AP_recv)
        self.horizontalLayout_5.addLayout(self.AP_verLayout_recv)
        self.AP_verLayout_right = QtWidgets.QVBoxLayout()
        self.AP_verLayout_right.setObjectName("AP_verLayout_right")
        spacerItem = QtWidgets.QSpacerItem(0, 800, QtWidgets.QSizePolicy.Minimum,
                                           QtWidgets.QSizePolicy.Preferred)
        self.AP_verLayout_right.addItem(spacerItem)
        self.Btn_AP_clearBrowser = QtWidgets.QPushButton(self.AP)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.Btn_AP_clearBrowser.sizePolicy().hasHeightForWidth())
        self.Btn_AP_clearBrowser.setSizePolicy(sizePolicy)
        self.Btn_AP_clearBrowser.setMinimumSize(QtCore.QSize(93, 28))
        self.Btn_AP_clearBrowser.setStyleSheet("background-color: #F4F8F9;\n"
                                               "border-style: outset;\n"
                                               "border-width: 2px;\n"
                                               "border-radius: 3px;\n"
                                               "border-color: #5A8EF4;\n"
                                               "color:#5A8EF4;\n"
                                               "font: bold 16px;\n"
                                               "")
        self.Btn_AP_clearBrowser.setObjectName("Btn_AP_clearBrowser")
        self.AP_verLayout_right.addWidget(self.Btn_AP_clearBrowser)
        self.horizontalLayout_5.addLayout(self.AP_verLayout_right)
        self.tabWidget.addTab(self.AP, "")
        self.CP = QtWidgets.QWidget()
        self.CP.setObjectName("CP")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.CP)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.GroupBox_CP_test = QtWidgets.QGroupBox(self.CP)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.GroupBox_CP_test.sizePolicy().hasHeightForWidth())
        self.GroupBox_CP_test.setSizePolicy(sizePolicy)
        self.GroupBox_CP_test.setMinimumSize(QtCore.QSize(240, 0))
        self.GroupBox_CP_test.setMaximumSize(QtCore.QSize(180, 16777215))
        self.GroupBox_CP_test.setStyleSheet("border:none;")
        self.GroupBox_CP_test.setTitle("")
        self.GroupBox_CP_test.setObjectName("GroupBox_CP_test")
        self.Btn_port_close = QtWidgets.QPushButton(self.GroupBox_CP_test)
        self.Btn_port_close.setGeometry(QtCore.QRect(130, 140, 90, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_port_close.sizePolicy().hasHeightForWidth())
        self.Btn_port_close.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Btn_port_close.setFont(font)
        self.Btn_port_close.setStyleSheet("background-color: white;\n"
                                          "border-style: outset;\n"
                                          "border-width: 2px;\n"
                                          "border-radius: 3px;\n"
                                          "border-color: #5A8EF4;\n"
                                          "color:#5A8EF4;\n"
                                          "font: bold 16px;\n"
                                          "")
        self.Btn_port_close.setObjectName("Btn_port_close")
        self.Btn_port_open = QtWidgets.QPushButton(self.GroupBox_CP_test)
        self.Btn_port_open.setGeometry(QtCore.QRect(20, 140, 90, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_port_open.sizePolicy().hasHeightForWidth())
        self.Btn_port_open.setSizePolicy(sizePolicy)
        self.Btn_port_open.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Btn_port_open.setFont(font)
        self.Btn_port_open.setStyleSheet("background-color: white;\n"
                                         "border-style: outset;\n"
                                         "border-width: 2px;\n"
                                         "border-radius: 3px;\n"
                                         "border-color: #5A8EF4;\n"
                                         "color:#5A8EF4;\n"
                                         "font: bold 16px;\n"
                                         "")
        self.Btn_port_open.setObjectName("Btn_port_open")
        self.ComboBox_port_select = QtWidgets.QComboBox(self.GroupBox_CP_test)
        self.ComboBox_port_select.setGeometry(QtCore.QRect(20, 80, 203, 43))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComboBox_port_select.sizePolicy().hasHeightForWidth())
        self.ComboBox_port_select.setSizePolicy(sizePolicy)
        self.ComboBox_port_select.setStyleSheet("background-color: white;\n"
                                                "border-style: outset;\n"
                                                "border-width: 2px;\n"
                                                "border-radius: 10px;\n"
                                                "border-color: #5A8EF4;\n"
                                                "color:#5A8EF4;\n"
                                                "font: bold 18px;\n"
                                                "min-width: 10em;")
        self.ComboBox_port_select.setObjectName("ComboBox_port_select")
        self.Btn_port_check = QtWidgets.QPushButton(self.GroupBox_CP_test)
        self.Btn_port_check.setGeometry(QtCore.QRect(20, 20, 203, 43))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_port_check.sizePolicy().hasHeightForWidth())
        self.Btn_port_check.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Btn_port_check.setFont(font)
        self.Btn_port_check.setStyleSheet("background-color: white;\n"
                                          "border-style: outset;\n"
                                          "border-width: 2px;\n"
                                          "border-radius: 10px;\n"
                                          "border-color: #5A8EF4;\n"
                                          "color:#5A8EF4;\n"
                                          "font: bold 18px;\n"
                                          "")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("img/ue_check.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Btn_port_check.setIcon(icon2)
        self.Btn_port_check.setIconSize(QtCore.QSize(25, 25))
        self.Btn_port_check.setObjectName("Btn_port_check")
        self.Btn_CP_runTest = QtWidgets.QPushButton(self.GroupBox_CP_test)
        self.Btn_CP_runTest.setGeometry(QtCore.QRect(20, 510, 203, 43))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Btn_CP_runTest.setFont(font)
        self.Btn_CP_runTest.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 #EEB84B, stop:0.95 #EFD560);\n"
            "border-style: outset;\n"
            "border-width: 2px;\n"
            "border-radius: 10px;\n"
            "border-color: #F7B500;\n"
            "color:white;\n"
            "font: bold 18px;\n"
            "min-width: 10em;")
        self.Btn_CP_runTest.setObjectName("Btn_CP_runTest")
        self.Btn_CP_stopTest = QtWidgets.QPushButton(self.GroupBox_CP_test)
        self.Btn_CP_stopTest.setGeometry(QtCore.QRect(20, 570, 164, 35))
        self.Btn_CP_stopTest.setMinimumSize(QtCore.QSize(164, 0))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Btn_CP_stopTest.setFont(font)
        self.Btn_CP_stopTest.setStyleSheet("background-color: white;\n"
                                           "border-style: outset;\n"
                                           "border-width: 2px;\n"
                                           "border-radius: 10px;\n"
                                           "border-color: #E02020;\n"
                                           "color:#E02020;\n"
                                           "font: bold 16px;\n"
                                           "min-width: 10em;")
        self.Btn_CP_stopTest.setIcon(icon1)
        self.Btn_CP_stopTest.setIconSize(QtCore.QSize(25, 25))
        self.Btn_CP_stopTest.setObjectName("Btn_CP_stopTest")
        self.Label_CP_test_times = QtWidgets.QLabel(self.GroupBox_CP_test)
        self.Label_CP_test_times.setGeometry(QtCore.QRect(30, 460, 81, 25))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(11)
        self.Label_CP_test_times.setFont(font)
        self.Label_CP_test_times.setObjectName("Label_CP_test_times")
        self.Ledit_CP_test_times = QtWidgets.QLineEdit(self.GroupBox_CP_test)
        self.Ledit_CP_test_times.setGeometry(QtCore.QRect(110, 450, 101, 43))
        self.Ledit_CP_test_times.setStyleSheet("background-color: white;\n"
                                               "border-style: outset;\n"
                                               "border-width: 2px;\n"
                                               "border-radius: 4px;\n"
                                               "border-color: rgb(0, 170, 255);\n"
                                               "color:rgb(0, 170, 255);\n"
                                               "font: bold 18px;")
        self.Ledit_CP_test_times.setAlignment(QtCore.Qt.AlignCenter)
        self.Ledit_CP_test_times.setObjectName("Ledit_CP_test_times")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.GroupBox_CP_test)
        self.textBrowser_2.setGeometry(QtCore.QRect(20, 185, 203, 176))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setStyleSheet("border:none;\n"
                                         "background-color: #EAEEF6;\n"
                                         "border-color: #ADBFE2;\n"
                                         "border-style: outset;\n"
                                         "border-width: 2px;\n"
                                         "border-radius: 5px;\n"
                                         "min-width: 10em;")
        self.textBrowser_2.setLineWidth(1)
        self.textBrowser_2.setReadOnly(False)
        self.textBrowser_2.setMarkdown("")
        self.textBrowser_2.setAcceptRichText(True)
        self.textBrowser_2.setCursorWidth(1)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.Btn_select_cp_case = QtWidgets.QPushButton(self.GroupBox_CP_test)
        self.Btn_select_cp_case.setGeometry(QtCore.QRect(20, 380, 200, 51))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Btn_select_cp_case.setFont(font)
        self.Btn_select_cp_case.setStyleSheet("background-color: rgb(69, 119, 255);\n"
                                              "border-style: outset;\n"
                                              "border-radius: 10px;\n"
                                              "color:white;\n"
                                              "font: bold 18px;\n"
                                              "min-width: 10em;")
        self.Btn_select_cp_case.setObjectName("Btn_select_cp_case")
        self.horizontalLayout_3.addWidget(self.GroupBox_CP_test)
        self.verticalLayout_CP_recv = QtWidgets.QVBoxLayout()
        self.verticalLayout_CP_recv.setObjectName("verticalLayout_CP_recv")
        self.GroupBox_CP_recv = QtWidgets.QGroupBox(self.CP)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(9)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.GroupBox_CP_recv.sizePolicy().hasHeightForWidth())
        self.GroupBox_CP_recv.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(9)
        self.GroupBox_CP_recv.setFont(font)
        self.GroupBox_CP_recv.setObjectName("GroupBox_CP_recv")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.GroupBox_CP_recv)
        self.verticalLayout_8.setContentsMargins(-1, 5, -1, 5)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.TextBrowser_CP_recv = QtWidgets.QTextBrowser(self.GroupBox_CP_recv)
        self.TextBrowser_CP_recv.setObjectName("TextBrowser_CP_recv")
        self.verticalLayout_8.addWidget(self.TextBrowser_CP_recv)
        self.verticalLayout_CP_recv.addWidget(self.GroupBox_CP_recv)
        self.GroupBox_CP_send = QtWidgets.QGroupBox(self.CP)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.GroupBox_CP_send.sizePolicy().hasHeightForWidth())
        self.GroupBox_CP_send.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("等线")
        self.GroupBox_CP_send.setFont(font)
        self.GroupBox_CP_send.setObjectName("GroupBox_CP_send")
        self.gridLayout = QtWidgets.QGridLayout(self.GroupBox_CP_send)
        self.gridLayout.setObjectName("gridLayout")
        self.TextEdit_CP_send = QtWidgets.QTextEdit(self.GroupBox_CP_send)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TextEdit_CP_send.sizePolicy().hasHeightForWidth())
        self.TextEdit_CP_send.setSizePolicy(sizePolicy)
        self.TextEdit_CP_send.setObjectName("TextEdit_CP_send")
        self.gridLayout.addWidget(self.TextEdit_CP_send, 0, 0, 1, 1)
        self.verticalLayout_CP_recv.addWidget(self.GroupBox_CP_send)
        self.horizontalLayout_3.addLayout(self.verticalLayout_CP_recv)
        self.CP_verLayout_right = QtWidgets.QVBoxLayout()
        self.CP_verLayout_right.setObjectName("CP_verLayout_right")
        spacerItem1 = QtWidgets.QSpacerItem(0, 400, QtWidgets.QSizePolicy.Minimum,
                                            QtWidgets.QSizePolicy.Preferred)
        self.CP_verLayout_right.addItem(spacerItem1)
        self.Btn_CP_clear_recvBrowser = QtWidgets.QPushButton(self.CP)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.Btn_CP_clear_recvBrowser.sizePolicy().hasHeightForWidth())
        self.Btn_CP_clear_recvBrowser.setSizePolicy(sizePolicy)
        self.Btn_CP_clear_recvBrowser.setMinimumSize(QtCore.QSize(93, 28))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Btn_CP_clear_recvBrowser.setFont(font)
        self.Btn_CP_clear_recvBrowser.setStyleSheet("background-color: white;\n"
                                                    "border-style: outset;\n"
                                                    "border-width: 2px;\n"
                                                    "border-radius: 3px;\n"
                                                    "border-color: #5A8EF4;\n"
                                                    "color:#5A8EF4;\n"
                                                    "font: bold 16px;\n"
                                                    "")
        self.Btn_CP_clear_recvBrowser.setObjectName("Btn_CP_clear_recvBrowser")
        self.CP_verLayout_right.addWidget(self.Btn_CP_clear_recvBrowser)
        spacerItem2 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum,
                                            QtWidgets.QSizePolicy.Expanding)
        self.CP_verLayout_right.addItem(spacerItem2)
        self.Btn_CP_send = QtWidgets.QPushButton(self.CP)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.Btn_CP_send.sizePolicy().hasHeightForWidth())
        self.Btn_CP_send.setSizePolicy(sizePolicy)
        self.Btn_CP_send.setMinimumSize(QtCore.QSize(93, 28))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Btn_CP_send.setFont(font)
        self.Btn_CP_send.setStyleSheet("background-color: white;\n"
                                       "border-style: outset;\n"
                                       "border-width: 2px;\n"
                                       "border-radius: 3px;\n"
                                       "border-color: #5A8EF4;\n"
                                       "color:#5A8EF4;\n"
                                       "font: bold 16px;\n"
                                       "")
        self.Btn_CP_send.setObjectName("Btn_CP_send")
        self.CP_verLayout_right.addWidget(self.Btn_CP_send)
        self.Btn_CP_clear_sendEdit = QtWidgets.QPushButton(self.CP)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.Btn_CP_clear_sendEdit.sizePolicy().hasHeightForWidth())
        self.Btn_CP_clear_sendEdit.setSizePolicy(sizePolicy)
        self.Btn_CP_clear_sendEdit.setMinimumSize(QtCore.QSize(93, 28))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Btn_CP_clear_sendEdit.setFont(font)
        self.Btn_CP_clear_sendEdit.setStyleSheet("background-color: white;\n"
                                                 "border-style: outset;\n"
                                                 "border-width: 2px;\n"
                                                 "border-radius: 3px;\n"
                                                 "border-color: #5A8EF4;\n"
                                                 "color:#5A8EF4;\n"
                                                 "font: bold 16px;\n"
                                                 "")
        self.Btn_CP_clear_sendEdit.setObjectName("Btn_CP_clear_sendEdit")
        self.CP_verLayout_right.addWidget(self.Btn_CP_clear_sendEdit)
        self.horizontalLayout_3.addLayout(self.CP_verLayout_right)
        self.tabWidget.addTab(self.CP, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 968, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLog = QtWidgets.QAction(MainWindow)
        self.actionLog.setObjectName("actionLog")
        self.actionAT = QtWidgets.QAction(MainWindow)
        self.actionAT.setObjectName("actionAT")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.Btn_dev_check.clicked.connect(self.ComboBox_dev_select.update)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Btn_dev_check.setText(_translate("MainWindow", " 设备检测"))
        self.ComboBox_dev_select.setPlaceholderText(_translate("MainWindow", "设备选择"))
        self.Btn_AP_runTest.setStatusTip(_translate("MainWindow", "测试项：{}"))
        self.Btn_AP_runTest.setText(_translate("MainWindow", "开始测试"))
        self.Btn_AP_runTest.setProperty("setAlignment", _translate("MainWindow", "Qt.AlignCenter"))
        self.Btn_AP_stopTest.setStatusTip(_translate("MainWindow", "当前测试完成后结束测试"))
        self.Btn_AP_stopTest.setText(_translate("MainWindow", "停止"))
        self.Label_AP_test_times.setText(_translate("MainWindow", "测试次数"))
        self.Btn_select_ap_case.setText(_translate("MainWindow", "测试项选择"))
        self.textBrowser.setHtml(_translate("MainWindow",
                                            "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" "
                                            "\"http://www.w3.org/TR/REC-html40/strict.dtd\">\n "
                                            "<html><head><meta name=\"qrichtext\" content=\"1\" /><style "
                                            "type=\"text/css\">\n "
                                            "p, li { white-space: pre-wrap; }\n"
                                            "</style></head><body style=\" font-family:\'微软雅黑\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
                                            "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.GroupBox_AP_recv.setTitle(_translate("MainWindow", "接收区"))
        self.TextBrowser_AP_recv.setProperty("align", _translate("MainWindow", "center"))
        self.Btn_AP_clearBrowser.setStatusTip(_translate("MainWindow", "清除接收区内容"))
        self.Btn_AP_clearBrowser.setText(_translate("MainWindow", "清除"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.AP), _translate("MainWindow", "AP"))
        self.Btn_port_close.setText(_translate("MainWindow", "关闭串口"))
        self.Btn_port_open.setText(_translate("MainWindow", "打开串口"))
        self.ComboBox_port_select.setStatusTip(_translate("MainWindow", "显示当前选择的串口"))
        self.Btn_port_check.setStatusTip(_translate("MainWindow", "检测当前连接PC的串口"))
        self.Btn_port_check.setText(_translate("MainWindow", " 检测串口"))
        self.Btn_CP_runTest.setStatusTip(_translate("MainWindow", "测试项：{}".format(Word.be_testcase)))
        self.Btn_CP_runTest.setText(_translate("MainWindow", "开始测试"))
        self.Btn_CP_stopTest.setStatusTip(_translate("MainWindow", "当前测试完成后结束测试"))
        self.Btn_CP_stopTest.setText(_translate("MainWindow", "停止"))
        self.Label_CP_test_times.setText(_translate("MainWindow", "测试次数"))
        self.textBrowser_2.setHtml(_translate("MainWindow",
                                              "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                              "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                              "p, li { white-space: pre-wrap; }\n"
                                              "</style></head><body style=\" font-family:\'微软雅黑\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
                                              "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.Btn_select_cp_case.setText(_translate("MainWindow", "测试项选择"))
        self.GroupBox_CP_recv.setTitle(_translate("MainWindow", "接收区"))
        self.GroupBox_CP_send.setTitle(_translate("MainWindow", "发送区"))
        self.Btn_CP_clear_recvBrowser.setStatusTip(_translate("MainWindow", "清除接收区内容"))
        self.Btn_CP_clear_recvBrowser.setText(_translate("MainWindow", "清除"))
        self.Btn_CP_send.setText(_translate("MainWindow", "发送"))
        self.Btn_CP_send.setShortcut(_translate("MainWindow", "Return"))
        self.Btn_CP_clear_sendEdit.setStatusTip(_translate("MainWindow", "清除发送区内容"))
        self.Btn_CP_clear_sendEdit.setText(_translate("MainWindow", "清除"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.CP), _translate("MainWindow", "CP"))
        self.actionLog.setText(_translate("MainWindow", "Log"))
        self.actionAT.setText(_translate("MainWindow", "AT"))
