# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(426, 413)
        self.Label_calledNumber = QtWidgets.QLabel(Dialog)
        self.Label_calledNumber.setGeometry(QtCore.QRect(40, 60, 91, 25))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.Label_calledNumber.setFont(font)
        self.Label_calledNumber.setObjectName("Label_calledNumber")
        self.Label_callInterval = QtWidgets.QLabel(Dialog)
        self.Label_callInterval.setGeometry(QtCore.QRect(40, 100, 151, 25))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.Label_callInterval.setFont(font)
        self.Label_callInterval.setObjectName("Label_callInterval")
        self.LineEdit_calledNumber = QtWidgets.QLineEdit(Dialog)
        self.LineEdit_calledNumber.setGeometry(QtCore.QRect(200, 60, 191, 25))
        self.LineEdit_calledNumber.setObjectName("LineEdit_calledNumber")
        self.LineEdit_callInterval = QtWidgets.QLineEdit(Dialog)
        self.LineEdit_callInterval.setGeometry(QtCore.QRect(200, 100, 191, 25))
        self.LineEdit_callInterval.setObjectName("LineEdit_callInterval")
        self.Btn_settings_save = QtWidgets.QPushButton(Dialog)
        self.Btn_settings_save.setGeometry(QtCore.QRect(200, 360, 93, 28))
        self.Btn_settings_save.setObjectName("Btn_settings_save")
        self.Btn_settings_cancel = QtWidgets.QPushButton(Dialog)
        self.Btn_settings_cancel.setGeometry(QtCore.QRect(310, 360, 93, 28))
        self.Btn_settings_cancel.setObjectName("Btn_settings_cancel")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(40, 140, 72, 15))
        self.label.setText("")
        self.label.setObjectName("label")
        self.Label_getLog = QtWidgets.QLabel(Dialog)
        self.Label_getLog.setGeometry(QtCore.QRect(40, 140, 151, 25))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.Label_getLog.setFont(font)
        self.Label_getLog.setObjectName("Label_getLog")
        self.RadioBtn_getLog_true = QtWidgets.QRadioButton(Dialog)
        self.RadioBtn_getLog_true.setGeometry(QtCore.QRect(200, 150, 61, 19))
        self.RadioBtn_getLog_true.setObjectName("RadioBtn_getLog_true")
        self.RadioBtn_getLog_false = QtWidgets.QRadioButton(Dialog)
        self.RadioBtn_getLog_false.setGeometry(QtCore.QRect(280, 150, 61, 19))
        self.RadioBtn_getLog_false.setChecked(True)
        self.RadioBtn_getLog_false.setObjectName("RadioBtn_getLog_false")
        self.Label_logPath = QtWidgets.QLabel(Dialog)
        self.Label_logPath.setGeometry(QtCore.QRect(40, 180, 151, 25))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.Label_logPath.setFont(font)
        self.Label_logPath.setObjectName("Label_logPath")
        self.LineEdit_logPath = QtWidgets.QLineEdit(Dialog)
        self.LineEdit_logPath.setGeometry(QtCore.QRect(150, 180, 241, 25))
        self.LineEdit_logPath.setObjectName("LineEdit_logPath")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Label_calledNumber.setText(_translate("Dialog", "被叫号码:"))
        self.Label_callInterval.setText(_translate("Dialog", "通话测试间隔（秒）:"))
        self.Btn_settings_save.setText(_translate("Dialog", "确认"))
        self.Btn_settings_cancel.setText(_translate("Dialog", "取消"))
        self.Label_getLog.setText(_translate("Dialog", "Logcat抓取"))
        self.RadioBtn_getLog_true.setText(_translate("Dialog", "开启"))
        self.RadioBtn_getLog_false.setText(_translate("Dialog", "关闭"))
        self.Label_logPath.setText(_translate("Dialog", "Log保存路径"))
